"use client";

import { useActionState, useState } from "react";
import { linkCandidateMacIdentityAction, mergeMacIdentitiesAction, type MacIdentityActionState } from "@/app/(dashboard)/candidates/actions";
import { Button } from "@/components/ui/button";

type Identity = { id: string; created_at: string };
type Summary = { id: string; status: "active" | "merged"; mergedIntoIdentityId: string | null; verifiedAt: string | null; candidateCount: number; operations: Array<{ id: string; operationType: string; reason: string | null; createdAt: string }>; sessions: Array<{ id: string; title: string; endDate: string; trainingType: string }>; macDueDate: string | null } | null;
const emptyState: MacIdentityActionState = {};

export function MacIdentityPanel({ candidateId, identity, availableIdentities, isAdmin }: { candidateId: string; identity: Summary; availableIdentities: Identity[]; isAdmin: boolean }) {
  const [linkState, linkAction, linking] = useActionState(linkCandidateMacIdentityAction, emptyState);
  const [mergeState, mergeAction, merging] = useActionState(mergeMacIdentitiesAction, emptyState);
  const [showControls, setShowControls] = useState(false);
  const status = identity?.status === "active" && identity.verifiedAt ? "Identité MAC vérifiée" : "Identité MAC à vérifier";
  return <section className="grid gap-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{status}</p>{identity ? <span className="text-xs text-ink/55">{identity.candidateCount} dossier(s) rattaché(s)</span> : null}</div>
    <p className="text-sm text-ink/65">Cette identité est indépendante de l’email, de la société et du nom. Les rapprochements restent toujours une décision administrative explicite.</p>
    {identity?.macDueDate ? <p className="rounded-xl bg-canvas/60 px-3 py-2 text-sm">Échéance SST connue : {new Date(`${identity.macDueDate}T00:00:00`).toLocaleDateString("fr-FR")}</p> : <p className="text-sm text-ink/55">Aucune formation SST validée de référence n’est encore disponible.</p>}
    {identity?.sessions.length ? <details className="rounded-xl border border-ink/10 p-3 text-sm"><summary className="cursor-pointer font-semibold">Sessions et inscriptions rattachées</summary><ul className="mt-3 grid gap-2 text-ink/65">{identity.sessions.map((session) => <li key={session.id}>{session.title} — {session.trainingType === "mac_sst" ? "MAC SST" : session.trainingType === "sst_initial" ? "SST initiale" : session.trainingType}</li>)}</ul></details> : null}
    {identity?.status === "merged" ? <p className="rounded-xl bg-sand px-3 py-2 text-sm">Identité fusionnée : seul le dossier canonique déclenche les rappels MAC.</p> : null}
    {identity?.operations.length ? <details className="rounded-xl border border-ink/10 p-3 text-sm"><summary className="cursor-pointer font-semibold">Historique administratif</summary><ul className="mt-3 grid gap-2 text-ink/65">{identity.operations.map((operation) => <li key={operation.id}>{operation.operationType === "merged" ? "Regroupement" : operation.operationType === "linked" ? "Rattachement" : operation.operationType === "backfill" ? "Backfill" : "Création"}{operation.reason ? ` — ${operation.reason}` : ""}</li>)}</ul></details> : null}
    {isAdmin && identity ? <><Button type="button" variant="secondary" onClick={() => setShowControls((value) => !value)}>{showControls ? "Annuler les modifications" : "Gérer l’identité MAC"}</Button>{showControls ? <div className="grid gap-4 rounded-2xl border border-ink/10 p-4"><form action={linkAction} className="grid gap-3"><input type="hidden" name="candidateId" value={candidateId} /><label className="grid gap-1 text-sm font-medium">Rattacher ce dossier à une identité existante<select name="identityId" defaultValue="" required className="rounded-xl border border-ink/10 bg-white px-3 py-2"><option value="" disabled>Choisir l’identité canonique</option>{availableIdentities.filter((item) => item.id !== identity.id).map((item) => <option key={item.id} value={item.id}>Identité créée le {new Date(item.created_at).toLocaleDateString("fr-FR")}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Motif administratif<textarea name="reason" required minLength={3} className="rounded-xl border border-ink/10 p-2" /></label><Button type="submit" disabled={linking}>{linking ? "Rattachement…" : "Confirmer le rattachement"}</Button>{linkState.error ? <p role="alert" className="text-sm text-accent">{linkState.error}</p> : null}{linkState.success ? <p role="status" className="text-sm text-pine">{linkState.success}</p> : null}</form><form action={mergeAction} className="grid gap-3 border-t border-ink/10 pt-4"><input type="hidden" name="candidateId" value={candidateId} /><input type="hidden" name="secondaryIdentityId" value={identity.id} /><label className="grid gap-1 text-sm font-medium">Regrouper l’identité affichée dans<select name="canonicalIdentityId" defaultValue="" required className="rounded-xl border border-ink/10 bg-white px-3 py-2"><option value="" disabled>Choisir l’identité canonique</option>{availableIdentities.filter((item) => item.id !== identity.id).map((item) => <option key={item.id} value={item.id}>Identité créée le {new Date(item.created_at).toLocaleDateString("fr-FR")}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Motif administratif<textarea name="reason" required minLength={3} className="rounded-xl border border-ink/10 p-2" /></label><Button type="submit" disabled={merging}>{merging ? "Regroupement…" : "Confirmer le regroupement"}</Button>{mergeState.error ? <p role="alert" className="text-sm text-accent">{mergeState.error}</p> : null}{mergeState.success ? <p role="status" className="text-sm text-pine">{mergeState.success}</p> : null}</form></div> : null}</> : null}
  </section>;
}
