import Link from "next/link";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { TrainingNeedsAnswersSummary, TrainingNeedsStatusBadge } from "@/components/training-needs/internal-summary";
import { getInternalTrainingNeedsAnalysis } from "@/lib/training-needs/internal";
import { ResourceNotFoundError, AuthorizationError } from "@/lib/auth";

export const dynamic = "force-dynamic";
export default async function TrainingNeedsDetailPage({ params }: { params: Promise<{ analysisId: string }> }) { const { analysisId } = await params; try { const analysis = await getInternalTrainingNeedsAnalysis(analysisId); return <main className="mx-auto grid max-w-5xl gap-4"><div className="flex flex-wrap gap-3"><Link href={`/companies/${analysis.company_id}`} className="text-sm font-semibold text-pine underline">Retour à la société</Link><Link href={`/quotes/${analysis.quote_id}`} className="text-sm font-semibold text-pine underline">Retour au devis</Link></div><Card><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm uppercase tracking-[0.2em] text-ink/45">Analyse des besoins</p><h1 className="mt-2 text-3xl font-bold">{analysis.quote_snapshot.title}</h1><p className="mt-1 text-sm text-ink/65">{analysis.quote_snapshot.companyName} · {analysis.quote_snapshot.quoteNumber}</p></div><TrainingNeedsStatusBadge status={analysis.status} /></div><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><p>Progression : {analysis.progress_percent}%</p><p>Répondant : {analysis.respondent_name || "Non renseigné"}</p><p>Email : {analysis.respondent_email || "Non renseigné"}</p><p>Fonction : {analysis.respondent_role || "Non renseignée"}</p></div></Card><Card><h2 className="text-2xl font-bold">Réponses</h2><div className="mt-5"><TrainingNeedsAnswersSummary answers={analysis.answers} /></div></Card></main>; } catch (error) { if (error instanceof ResourceNotFoundError || error instanceof AuthorizationError) notFound(); throw error; } }
