import { z } from "zod";
import type { TrainingNeedsTrainingType } from "./types";

const text = (max: number) => z.preprocess((value) => typeof value === "string" ? value.trim().replace(/\s+/g, " ") : value, z.string().max(max));
// These fields are displayed only when their related "Autre" or accessibility
// option is selected.  An absent value therefore means "not applicable"; the
// conditional checks below still require a meaningful value when applicable.
const conditionalText = (max: number) => z.preprocess((value) => value === undefined || value === null ? "" : value, text(max));
const phone = z.preprocess((value) => typeof value === "string" ? value.trim().replace(/[\s.-]/g, "") : value, z.string().regex(/^\+?[0-9]{6,15}$/, "Téléphone invalide."));
const list = <T extends z.ZodTypeAny>(item: T) => z.array(item).max(20).refine((values) => new Set(values).size === values.length, "Les valeurs doivent être uniques.");
const select = <T extends readonly [string, ...string[]]>(values: T) => z.enum(values);
const yn = select(["yes", "no", "to_check"]);

const respondent = z.object({ name: text(80), firstName: text(80), role: text(120), email: z.preprocess((value) => typeof value === "string" ? value.trim().toLowerCase() : value, z.string().email().max(254)), phone }).strict();
const origins = list(select(["regulatory", "initial_training", "skills_maintenance", "risk_prevention", "management_request", "employee_request", "activity_change", "accident_incident", "audit", "other"]));
const documents = list(select(["duerp", "safety_instructions", "prevention_plan", "emergency_procedures", "site_plan", "sanitary_plan", "hygiene_protocols", "other", "none"]));

export const trainingNeedsCommonSchemaV1 = z.object({
  respondent, objectives: text(2000), participantCount: z.number().int().min(1).max(500), participantProfiles: list(text(160)), accessibilityNeeds: text(1000), constraints: text(1000), preferredDates: text(500), notes: text(2000),
  companyWorkforce: z.number().int().min(1).max(1_000_000), businessSector: text(160), desiredLocation: text(300), requestOrigins: origins, requestOriginOther: conditionalText(500), requestReasons: text(2000), experienceLevel: select(["new", "experienced", "mixed"]), frenchLevel: select(["yes", "no", "to_check"]), learningAdaptations: text(1000), accessibilityStatus: select(["no", "yes", "unknown"]), accessibilityAdaptations: conditionalText(1000), scheduleConstraints: text(1000), siteAccessConstraints: text(1000), requiredPpe: text(500), roomAvailable: yn, workplaceVisitPossible: yn,
  activityDescription: text(2000), concernedWorkstations: text(2000), identifiedRisks: text(2000), recentIncidents: text(2000), internalDocuments: documents, internalDocumentsOther: conditionalText(500), previousSimilarTraining: select(["yes", "no", "unknown"]), previousTrainingTitle: text(300), previousTrainingDate: text(100), contractSummary: conditionalText(4000)
}).passthrough().superRefine((data, context) => {
  if (data.requestOrigins.includes("other") && !data.requestOriginOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["requestOriginOther"], message: "Précisez l’autre origine." });
  if (data.internalDocuments.includes("other") && !data.internalDocumentsOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["internalDocumentsOther"], message: "Précisez l’autre document." });
  if (data.previousSimilarTraining === "yes" && (!data.previousTrainingTitle || !data.previousTrainingDate)) context.addIssue({ code: z.ZodIssueCode.custom, path: ["previousTrainingTitle"], message: "Précisez la formation antérieure et sa date." });
});

export const trainingNeedsSstInitialSchemaV1 = z.object({ firstAidExperience: select(["none", "occasional", "regular"]), currentSstEmployees: select(["yes", "no", "unknown"]), currentSstCount: z.number().int().min(0).max(500), coverageAreas: text(1000), workplaceRisks: list(select(["falls", "manual_handling", "machines", "electricity", "chemical", "burns", "cuts", "choking", "malaise", "traffic", "isolated_work", "public", "other"])), workplaceRisksOther: conditionalText(500), exerciseSituations: text(2000), preventionAndFirstAidExpectations: text(2000), emergencyEquipment: list(select(["first_aid_kit", "defibrillator", "eyewash", "none", "other"])) }).strict().superRefine((data, context) => { if (data.workplaceRisks.includes("other") && !data.workplaceRisksOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["workplaceRisksOther"], message: "Précisez l’autre risque." }); });
export const trainingNeedsMacSstSchemaV1 = z.object({ certificateHolderCount: z.number().int().min(0).max(500), lastTrainingDate: text(100), certificatesAvailable: yn, certificateStatus: select(["valid", "expired", "unknown", "mixed"]), certificateReference: text(120), changesSinceTraining: list(select(["premises", "equipment", "risks", "organisation", "emergency_procedures", "accident_incident", "none", "other"])), changesOther: conditionalText(500), practiceNeeds: list(select(["protection", "prevention", "examination", "alert", "bleeding", "choking", "malaise", "burn", "trauma", "unconsciousness", "cardiac_defibrillator", "company_situations"])), observations: text(2000) }).strict().superRefine((data, context) => { if (data.changesSinceTraining.includes("other") && !data.changesOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["changesOther"], message: "Précisez l’autre changement." }); });
export const trainingNeedsHygieneSchemaV1 = z.object({ sector: select(["food_service", "retail", "healthcare", "industry", "other"]), sectorOther: conditionalText(160), establishmentType: text(160), participantActivities: list(select(["receiving", "storage", "preparation", "processing", "cooking", "cooling", "reheating", "service", "sales", "delivery", "cleaning", "waste", "traceability", "other"])), activitiesOther: conditionalText(500), sanitaryPlan: yn, hygieneProcedures: text(2000), hygieneRisks: list(select(["staff_hygiene", "hand_washing", "professional_attire", "cleaning", "temperatures", "cold_chain", "storage", "expiry_dates", "cross_contamination", "allergens", "traceability", "waste", "pests", "documentation", "other"])), hygieneRisksOther: conditionalText(500), recentInspection: select(["yes", "no", "unknown"]), inspectionRequests: text(2000), priorityObjectives: text(2000) }).strict().superRefine((data, context) => { if (data.sector === "other" && !data.sectorOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["sectorOther"], message: "Précisez l’autre domaine." }); if (data.participantActivities.includes("other") && !data.activitiesOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["activitiesOther"], message: "Précisez l’autre activité." }); if (data.hygieneRisks.includes("other") && !data.hygieneRisksOther) context.addIssue({ code: z.ZodIssueCode.custom, path: ["hygieneRisksOther"], message: "Précisez l’autre difficulté." }); });

const finalSchemas = { sst_initial: trainingNeedsCommonSchemaV1.innerType().extend({ specific: trainingNeedsSstInitialSchemaV1.innerType() }).strict(), mac_sst: trainingNeedsCommonSchemaV1.innerType().extend({ specific: trainingNeedsMacSstSchemaV1.innerType() }).strict(), hygiene: trainingNeedsCommonSchemaV1.innerType().extend({ specific: trainingNeedsHygieneSchemaV1.innerType() }).strict() } as const;
export function getTrainingNeedsFinalSchemaV1(trainingType: TrainingNeedsTrainingType) { return finalSchemas[trainingType]; }
export function validateTrainingNeedsFinalV1(trainingType: TrainingNeedsTrainingType, value: unknown) { const result = getTrainingNeedsFinalSchemaV1(trainingType).safeParse(value); if (!result.success) return result; const data = result.data; const specific = data.specific as Record<string, unknown>; const issues: z.ZodIssue[] = []; if (data.requestOrigins.includes("other") && !data.requestOriginOther) issues.push({ code: z.ZodIssueCode.custom, path: ["requestOriginOther"], message: "Précisez l’autre origine." }); if (data.internalDocuments.includes("other") && !data.internalDocumentsOther) issues.push({ code: z.ZodIssueCode.custom, path: ["internalDocumentsOther"], message: "Précisez l’autre document." }); if (data.previousSimilarTraining === "yes" && (!data.previousTrainingTitle || !data.previousTrainingDate)) issues.push({ code: z.ZodIssueCode.custom, path: ["previousTrainingTitle"], message: "Précisez la formation antérieure et sa date." }); if (trainingType === "sst_initial" && Array.isArray(specific.workplaceRisks) && specific.workplaceRisks.includes("other") && !specific.workplaceRisksOther) issues.push({ code: z.ZodIssueCode.custom, path: ["specific", "workplaceRisksOther"], message: "Précisez l’autre risque." }); if (trainingType === "mac_sst" && Array.isArray(specific.changesSinceTraining) && specific.changesSinceTraining.includes("other") && !specific.changesOther) issues.push({ code: z.ZodIssueCode.custom, path: ["specific", "changesOther"], message: "Précisez l’autre changement." }); if (trainingType === "hygiene" && ((specific.sector === "other" && !specific.sectorOther) || (Array.isArray(specific.participantActivities) && specific.participantActivities.includes("other") && !specific.activitiesOther) || (Array.isArray(specific.hygieneRisks) && specific.hygieneRisks.includes("other") && !specific.hygieneRisksOther))) issues.push({ code: z.ZodIssueCode.custom, path: ["specific"], message: "Précisez les champs « autre »." }); return issues.length ? { success: false as const, error: new z.ZodError(issues) } : result; }
const commonPartial = trainingNeedsCommonSchemaV1.innerType().deepPartial();
const partialSaveSchemas = { sst_initial: z.object({ answers: commonPartial.extend({ specific: trainingNeedsSstInitialSchemaV1.innerType().deepPartial().optional() }).strict() }).strict(), mac_sst: z.object({ answers: commonPartial.extend({ specific: trainingNeedsMacSstSchemaV1.innerType().deepPartial().optional() }).strict() }).strict(), hygiene: z.object({ answers: commonPartial.extend({ specific: trainingNeedsHygieneSchemaV1.innerType().deepPartial().optional() }).strict() }).strict() } as const;
export function getTrainingNeedsPartialSaveSchemaV1(trainingType: TrainingNeedsTrainingType) { return partialSaveSchemas[trainingType]; }
