import { describe, expect, it } from "vitest";
import { getTrainingNeedsPartialSaveSchemaV1, validateTrainingNeedsFinalV1 } from "./validation";

const common = { respondent: { name: " Martin ", firstName: " Jeanne ", role: " RH ", email: "JEANNE@EXAMPLE.TEST ", phone: "06 12 34 56 78" }, objectives: "Adapter", participantCount: 8, participantProfiles: ["Employés"], accessibilityNeeds: "Aucune", constraints: "Aucune", preferredDates: "Septembre", notes: "RAS", companyWorkforce: 50, businessSector: "Industrie", desiredLocation: "Paris", requestOrigins: ["risk_prevention"], requestOriginOther: "", requestReasons: "Prévenir", experienceLevel: "mixed", frenchLevel: "yes", learningAdaptations: "Aucune", accessibilityStatus: "no", accessibilityAdaptations: "", scheduleConstraints: "Aucune", siteAccessConstraints: "Aucune", requiredPpe: "Casque", roomAvailable: "yes", workplaceVisitPossible: "yes", activityDescription: "Atelier", concernedWorkstations: "Production", identifiedRisks: "Chute", recentIncidents: "Aucun", internalDocuments: ["duerp"], internalDocumentsOther: "", previousSimilarTraining: "no", previousTrainingTitle: "", previousTrainingDate: "" };
const specifics = { sst_initial: { firstAidExperience: "none", currentSstEmployees: "no", currentSstCount: 0, coverageAreas: "Atelier", workplaceRisks: ["falls"], workplaceRisksOther: "", exerciseSituations: "Chute", preventionAndFirstAidExpectations: "Alerter", emergencyEquipment: ["first_aid_kit"] }, mac_sst: { certificateHolderCount: 3, lastTrainingDate: "2025-01", certificatesAvailable: "yes", certificateStatus: "valid", certificateReference: "SST", changesSinceTraining: ["none"], changesOther: "", practiceNeeds: ["alert"], observations: "RAS" }, hygiene: { sector: "food_service", sectorOther: "", establishmentType: "Restaurant", participantActivities: ["cooking"], activitiesOther: "", sanitaryPlan: "yes", hygieneProcedures: "Existantes", hygieneRisks: ["allergens"], hygieneRisksOther: "", recentInspection: "no", inspectionRequests: "", priorityObjectives: "Allergènes" } } as const;
describe("questionnaire v1 complet", () => {
  it("normalizes phone, respondent and a partial save", () => { const result = getTrainingNeedsPartialSaveSchemaV1("sst_initial").parse({ answers: { respondent: common.respondent, requestOrigins: ["audit"] } }); expect(result.answers.respondent?.firstName).toBe("Jeanne"); expect(result.answers.respondent?.phone).toBe("0612345678"); });
  it.each(["sst_initial", "mac_sst", "hygiene"] as const)("validates complete %s answers", (type) => expect(validateTrainingNeedsFinalV1(type, { ...common, specific: specifics[type] }).success).toBe(true));
  it("does not require a hidden conditional field when its option is not selected", () => {
    const visibleCommon: Record<string, unknown> = { ...common }; delete visibleCommon.requestOriginOther; delete visibleCommon.accessibilityAdaptations; delete visibleCommon.internalDocumentsOther;
    const visibleSpecific: Record<string, unknown> = { ...specifics.sst_initial }; delete visibleSpecific.workplaceRisksOther;
    expect(validateTrainingNeedsFinalV1("sst_initial", { ...visibleCommon, specific: visibleSpecific }).success).toBe(true);
  });
  it("requires precision for other choices and rejects unknown properties", () => { expect(validateTrainingNeedsFinalV1("sst_initial", { ...common, requestOrigins: ["other"], requestOriginOther: "", specific: specifics.sst_initial }).success).toBe(false); expect(getTrainingNeedsPartialSaveSchemaV1("hygiene").safeParse({ answers: { token: "secret" } }).success).toBe(false); });
  it("rejects duplicate choices and invalid phone", () => { expect(getTrainingNeedsPartialSaveSchemaV1("sst_initial").safeParse({ answers: { requestOrigins: ["audit", "audit"] } }).success).toBe(false); expect(getTrainingNeedsPartialSaveSchemaV1("sst_initial").safeParse({ answers: { respondent: { ...common.respondent, phone: "bad" } } }).success).toBe(false); });
});
