"use client";

import { useActionState, useEffect, useMemo, useState } from "react";
import { addSharedTrainingResourceCommentAction, addSharedTrainingResourceVersionAction, changeSharedTrainingResourceStatusAction, createSharedTrainingResourceAction, openSharedTrainingResourceVersionAction, updateSharedTrainingResourceMetadataAction, type SharedResourceActionState } from "@/app/(dashboard)/shared-resources/actions";
import { Button } from "@/components/ui/button";

type Resource = { id: string; createdBy: string; resourceType: "file" | "link"; title: string; description: string | null; category: string; priority: string; requestedChange: string | null; status: string; trainingModuleId: string | null; moduleTitle: string | null; author: string | null; createdAt: string; lastActivityAt: string; integratedNote: string | null };
type Version = { id: string; resourceId: string; number: number; type: "file" | "link"; url: string | null; filename: string | null; mime: string | null; size: number | null; createdAt: string };
type Comment = { id: string; resourceId: string; body: string; author: string | null; createdAt: string };
type Audit = { id: string; resourceId: string; event: string; createdAt: string };
type Module = { id: string; title: string };
const initial: SharedResourceActionState = {};
const labelStatus: Record<string, string> = { to_review: "À examiner", approved: "Validé", integrated: "Intégré", rejected: "Refusé", obsolete: "Obsolète" };
const bytes = (value: number | null) => value == null ? "—" : value < 1024 * 1024 ? `${Math.round(value / 1024)} Ko` : `${(value / 1024 / 1024).toFixed(1)} Mo`;
const date = (value: string) => new Date(value).toLocaleDateString("fr-FR");

function OpenButton({ versionId }: { versionId: string }) { const [state, action, pending] = useActionState(openSharedTrainingResourceVersionAction, initial); useEffect(() => { if (state.url) window.open(state.url, "_blank", "noopener,noreferrer"); }, [state.url]); return <form action={action} className="inline-flex"><input type="hidden" name="versionId" value={versionId} /><Button type="submit" variant="secondary" disabled={pending}>{pending ? "Ouverture…" : "Ouvrir"}</Button>{state.error ? <span role="alert" className="ml-2 text-xs text-accent">{state.error}</span> : null}</form>; }

export function SharedResourcesWorkspace({ resources, versions, comments, audit, modules, isAdmin, viewerId }: { resources: Resource[]; versions: Version[]; comments: Comment[]; audit: Audit[]; modules: Module[]; isAdmin: boolean; viewerId: string }) {
  const [createState, createAction, creating] = useActionState(createSharedTrainingResourceAction, initial);
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [category, setCategory] = useState(""); const [priority, setPriority] = useState("");
  const [showAdd, setShowAdd] = useState(false);
  const visible = useMemo(() => resources.filter((resource) => (!query || `${resource.title} ${resource.description || ""}`.toLocaleLowerCase("fr-FR").includes(query.toLocaleLowerCase("fr-FR"))) && (!status || resource.status === status) && (!category || resource.category === category) && (!priority || resource.priority === priority)), [resources, query, status, category, priority]);
  const reviewCount = resources.filter((resource) => resource.status === "to_review").length;
  return <main className="grid gap-4"><section className="rounded-[28px] bg-white p-5 shadow-panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm uppercase tracking-[0.25em] text-ink/45">Collaboration privée</p><h1 className="mt-2 text-3xl font-bold">Ressources partagées</h1><p className="mt-2 max-w-3xl text-sm text-ink/65">Dépôts à examiner avant toute intégration manuelle dans une formation. Aucun module n’est modifié automatiquement.</p></div><Button type="button" onClick={() => setShowAdd((value) => !value)}>{showAdd ? "Fermer" : "Ajouter une ressource"}</Button></div><p className="mt-4 inline-flex rounded-full bg-sand px-3 py-1 text-sm font-semibold">{reviewCount} à examiner</p>
  {showAdd ? <form action={createAction} className="mt-5 grid gap-3 border-t border-ink/10 pt-5"><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Titre<input required name="title" className="rounded-xl border border-ink/10 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">Module concerné (facultatif)<select name="trainingModuleId" defaultValue="" className="rounded-xl border border-ink/10 px-3 py-2"><option value="">Non renseigné</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Catégorie<select name="category" defaultValue="support" className="rounded-xl border border-ink/10 px-3 py-2">{["support", "video", "regulation", "exercise", "quiz", "administrative", "other"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Priorité<select name="priority" defaultValue="normal" className="rounded-xl border border-ink/10 px-3 py-2">{["normal", "important", "urgent"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><label className="grid gap-1 text-sm font-medium">Document privé (PDF, DOCX, PPTX, XLSX, JPEG, PNG ou WebP — 20 Mo maximum)<input type="file" name="file" accept=".pdf,.docx,.pptx,.xlsx,.jpg,.jpeg,.png,.webp" /></label><p className="text-xs text-ink/55">Ou transmettez un lien HTTPS à la place d’un fichier. Aucun site externe n’est prévisualisé ou appelé par le serveur.</p><label className="grid gap-1 text-sm font-medium">Lien externe HTTPS (facultatif)<input type="url" name="externalUrl" placeholder="https://…" className="rounded-xl border border-ink/10 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">Description<textarea name="description" className="rounded-xl border border-ink/10 p-2" /></label><label className="grid gap-1 text-sm font-medium">Consigne ou modification demandée<textarea name="requestedChange" className="rounded-xl border border-ink/10 p-2" /></label><Button className="w-fit" type="submit" disabled={creating}>{creating ? "Dépôt…" : "Déposer pour examen"}</Button>{createState.error ? <p role="alert" className="text-sm text-accent">{createState.error}</p> : null}{createState.success ? <p role="status" className="text-sm text-pine">{createState.success}</p> : null}</form> : null}</section>
  <section className="rounded-[28px] bg-white p-5 shadow-panel"><div className="grid gap-3 md:grid-cols-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher titre ou description" className="rounded-xl border border-ink/10 px-3 py-2" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-ink/10 px-3 py-2"><option value="">Tous les statuts</option>{Object.entries(labelStatus).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-ink/10 px-3 py-2"><option value="">Toutes les catégories</option>{["support", "video", "regulation", "exercise", "quiz", "administrative", "other"].map((item) => <option key={item}>{item}</option>)}</select><select value={priority} onChange={(event) => setPriority(event.target.value)} className="rounded-xl border border-ink/10 px-3 py-2"><option value="">Toutes les priorités</option>{["normal", "important", "urgent"].map((item) => <option key={item}>{item}</option>)}</select></div>
  <div className="mt-5 grid gap-3">{visible.map((resource) => { const resourceVersions = versions.filter((version) => version.resourceId === resource.id); const resourceComments = comments.filter((comment) => comment.resourceId === resource.id); return <details key={resource.id} className="rounded-2xl border border-ink/10 p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{resource.title}</p><p className="mt-1 text-sm text-ink/60">{resource.resourceType === "file" ? "Fichier privé" : "Lien externe"} · {resource.author || "Non renseigné"} · {date(resource.lastActivityAt)} · {resource.moduleTitle || "Module non renseigné"}</p></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-sand px-2 py-1">{labelStatus[resource.status]}</span><span className="rounded-full bg-canvas px-2 py-1">{resource.priority}</span></div></div></summary><div className="mt-4 grid gap-4 border-t border-ink/10 pt-4 text-sm"><p>{resource.description || "Description non renseignée"}</p>{resource.requestedChange ? <p><strong>Demande :</strong> {resource.requestedChange}</p> : null}{(isAdmin || (resource.createdBy === viewerId && resource.status === "to_review")) ? <ResourceMetadataForm resource={resource} modules={modules} /> : null}<div><p className="font-semibold">Versions</p>{resourceVersions.length ? resourceVersions.map((version) => <div key={version.id} className="mt-2 flex flex-wrap items-center gap-2 rounded-xl bg-canvas/60 p-2"><span>v{version.number} · {version.filename || version.url || "Lien externe"} · {bytes(version.size)}</span>{version.type === "file" ? <OpenButton versionId={version.id} /> : <a href={version.url || "#"} target="_blank" rel="noopener noreferrer" className="rounded-full bg-sand px-3 py-1 font-semibold">Ouvrir le lien</a>}</div>) : <p className="text-ink/55">Aucune version.</p>}<ResourceVersionForm resourceId={resource.id} type={resource.resourceType} /></div><div><p className="font-semibold">Commentaires</p>{resourceComments.map((comment) => <p key={comment.id} className="mt-2 rounded-xl bg-canvas/60 p-2">{comment.body}<span className="ml-2 text-xs text-ink/55">{comment.author || "Non renseigné"} · {date(comment.createdAt)}</span></p>)}<ResourceCommentForm resourceId={resource.id} /></div>{isAdmin ? <ResourceAdminActions resourceId={resource.id} /> : null}<p className="text-xs text-ink/55">Historique : {audit.filter((item) => item.resourceId === resource.id).length} action(s) tracée(s). Aucune suppression physique n’est proposée.</p></div></details>; })}{!visible.length ? <p className="rounded-xl bg-canvas/60 p-4 text-sm text-ink/65">Aucune ressource ne correspond aux filtres.</p> : null}</div></section></main>;
}
function ResourceCommentForm({ resourceId }: { resourceId: string }) { const [state, action, pending] = useActionState(addSharedTrainingResourceCommentAction, initial); return <form action={action} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="resourceId" value={resourceId} /><input name="body" required placeholder="Ajouter un commentaire" className="min-w-56 flex-1 rounded-xl border border-ink/10 px-3 py-2" /><Button type="submit" variant="secondary" disabled={pending}>Commenter</Button>{state.error ? <span role="alert" className="text-xs text-accent">{state.error}</span> : null}</form>; }
function ResourceVersionForm({ resourceId, type }: { resourceId: string; type: "file" | "link" }) { const [state, action, pending] = useActionState(addSharedTrainingResourceVersionAction, initial); return <form action={action} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="resourceId" value={resourceId} />{type === "file" ? <label className="grid gap-1 text-xs">Nouvelle version<input type="file" name="file" required accept=".pdf,.docx,.pptx,.xlsx,.jpg,.jpeg,.png,.webp" /></label> : <label className="grid gap-1 text-xs">Nouveau lien HTTPS<input type="url" name="externalUrl" required className="rounded-xl border border-ink/10 px-3 py-2" /></label>}<Button type="submit" variant="secondary" disabled={pending}>{pending ? "Ajout…" : "Ajouter une version"}</Button>{state.error ? <span role="alert" className="text-xs text-accent">{state.error}</span> : null}</form>; }
function ResourceMetadataForm({ resource, modules }: { resource: Resource; modules: Module[] }) { const [state, action, pending] = useActionState(updateSharedTrainingResourceMetadataAction, initial); return <details className="rounded-xl border border-ink/10 p-3"><summary className="cursor-pointer font-semibold">Modifier les informations administratives</summary><form action={action} className="mt-3 grid gap-2"><input type="hidden" name="resourceId" value={resource.id} /><input name="title" defaultValue={resource.title} required className="rounded-xl border border-ink/10 px-3 py-2" /><textarea name="description" defaultValue={resource.description || ""} className="rounded-xl border border-ink/10 p-2" /><div className="grid gap-2 md:grid-cols-3"><select name="category" defaultValue={resource.category} className="rounded-xl border border-ink/10 px-3 py-2">{["support", "video", "regulation", "exercise", "quiz", "administrative", "other"].map((item) => <option key={item}>{item}</option>)}</select><select name="priority" defaultValue={resource.priority} className="rounded-xl border border-ink/10 px-3 py-2">{["normal", "important", "urgent"].map((item) => <option key={item}>{item}</option>)}</select><select name="trainingModuleId" defaultValue={resource.trainingModuleId || ""} className="rounded-xl border border-ink/10 px-3 py-2"><option value="">Module non renseigné</option>{modules.map((module) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></div><textarea name="requestedChange" defaultValue={resource.requestedChange || ""} placeholder="Consigne ou modification demandée" className="rounded-xl border border-ink/10 p-2" /><Button type="submit" className="w-fit" variant="secondary" disabled={pending}>Enregistrer</Button>{state.error ? <span role="alert" className="text-xs text-accent">{state.error}</span> : null}</form></details>; }
function ResourceAdminActions({ resourceId }: { resourceId: string }) { const [state, action, pending] = useActionState(changeSharedTrainingResourceStatusAction, initial); return <form action={action} className="grid gap-2 rounded-xl border border-ink/10 p-3"><p className="font-semibold">Décision administrative</p><input type="hidden" name="resourceId" value={resourceId} /><select name="status" defaultValue="approved" className="rounded-xl border border-ink/10 px-3 py-2">{Object.entries(labelStatus).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="integratedNote" placeholder="Note d’intégration si applicable" className="rounded-xl border border-ink/10 px-3 py-2" /><Button type="submit" className="w-fit" disabled={pending}>Mettre à jour</Button>{state.error ? <p role="alert" className="text-xs text-accent">{state.error}</p> : null}</form>; }
