import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { formatDate } from "@/lib/utils";
import type { TrainingNeedsRow } from "@/lib/training-needs/service-types";

const labels = { draft: "À envoyer", sent: "Envoyée", in_progress: "En cours", completed: "Validée", cancelled: "Annulée" } as const;
const types = { sst_initial: "SST initial", mac_sst: "MAC SST", hygiene: "Hygiène" } as const;
export function TrainingNeedsStatusBadge({ status, preQuote = false }: { status: TrainingNeedsRow["status"]; preQuote?: boolean }) { return <Badge tone={status === "completed" ? "success" : status === "in_progress" ? "warning" : "neutral"}>{status === "draft" && preQuote ? "À compléter" : labels[status]}</Badge>; }
export function TrainingNeedsSummaryCard({ analysis, showLink = true }: { analysis: TrainingNeedsRow; showLink?: boolean }) { const isPreQuote = !analysis.quote_id; return <div className="rounded-2xl border border-ink/10 bg-canvas/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{analysis.quote_snapshot.title}</p><p className="mt-1 text-sm text-ink/65">{analysis.quote_snapshot.quoteNumber} · {types[analysis.training_type]}</p></div><TrainingNeedsStatusBadge status={analysis.status} preQuote={isPreQuote} /></div><div className="mt-3 grid gap-1 text-sm text-ink/65 sm:grid-cols-2"><p>Progression : {analysis.progress_percent}%</p><p>Répondant : {analysis.respondent_name || "Non renseigné"}</p><p>Créée le {formatDate(analysis.created_at)}</p><p>Première ouverture : {analysis.first_opened_at ? formatDate(analysis.first_opened_at) : "—"}</p><p>Dernière sauvegarde : {analysis.last_saved_at ? formatDate(analysis.last_saved_at) : "—"}</p><p>Validation : {analysis.completed_at ? formatDate(analysis.completed_at) : "—"}</p></div>{showLink ? <div className="mt-4 flex flex-wrap gap-2"><Link href={`/training-needs/${analysis.id}`} className="inline-flex min-h-10 items-center rounded-full bg-pine px-4 text-sm font-semibold text-white">Consulter et modifier</Link>{isPreQuote && analysis.status === "completed" ? <Link href={`/companies/${analysis.company_id}?analysisId=${analysis.id}#devis`} className="inline-flex min-h-10 items-center rounded-full border border-pine px-4 text-sm font-semibold text-pine">Créer le devis</Link> : null}</div> : null}</div>; }
export function TrainingNeedsAnswersSummary({ answers }: { answers: Record<string, unknown> }) { return <dl className="grid gap-3">{Object.entries(answers).filter(([, value]) => value !== "" && value !== null && value !== undefined && (!Array.isArray(value) || value.length)).map(([key, value]) => <div key={key} className="rounded-xl bg-canvas/60 p-3"><dt className="text-xs font-semibold uppercase tracking-wide text-ink/50">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mt-1 text-sm text-ink/75">{Array.isArray(value) ? value.join(", ") : typeof value === "object" ? Object.values(value as Record<string, unknown>).filter(Boolean).join(" · ") : String(value)}</dd></div>)}</dl>; }
